<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.certiv.fluentmark</groupId>
	<artifactId>Fluentmark</artifactId>
	<version>1.5.4-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>FluentMark parent</name>
	<description>FluentMark parent</description>

	<organization>
		<name>Certiv Analytics</name>
		<url>http://www.certiv.net/</url>
	</organization>

	<prerequisites>
		<maven>3.0</maven>
	</prerequisites>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<!-- Beware of mixing usage of tycho >= 2.7.x and older versions with the same Maven repo.
		     see: https://github.com/eclipse-tycho/tycho/issues/725
		     If you do and encounter problem, you could try deleting / moving
		     ~/.m2/repository/.meta/p2-artifacts.properties file. -->
		<tycho.version>4.0.13</tycho.version>
		<!-- <tycho-extras.version>1.2.0</tycho-extras.version> -->
		<java.version>21</java.version>
	</properties>

	<modules>
		<module>target-platform/2025-03</module>
		<module>net.certiv.fluentmark.core</module>
		<module>net.certiv.fluentmark.ui</module>
		<module>net.certiv.fluentmark.feature</module>
		<module>net.certiv.fluentmark.site</module>
		<module>com.advantest.fluentmark.tests</module>
		<module>com.advantest.fluentmark.core.tests</module>
		<module>com.advantest.fluentmark.ui.tests</module>
	</modules>

	<build>
		<plugins>
		
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.6.2</version>
				<executions>
					<execution>
						<id>enforce-versions</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireMavenVersion>
									<version>[3.9.0,4)</version>
								</requireMavenVersion>
								<requireJavaVersion>
									<version>${java.version}</version>
								</requireJavaVersion>
							</rules>
						</configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho.version}</version>
				<extensions>true</extensions>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<release>${java.version}</release>
					<compilerArgs>
						<arg>-warn:-raw,unchecked</arg>
					</compilerArgs>
					<!-- use the JRE defined by Bundle-RequiredExecutionEnvironment in MANIFEST.MF,
				         for more details see https://tycho.eclipseprojects.io/doc/latest/tycho-compiler-plugin/compile-mojo.html#useJDK -->
					<useJdk>BREE</useJdk>
				</configuration>
			</plugin>
			
			<!--
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<argLine>${tycho.testArgLine} -Xms128m -Xmx4096m -Xss4m</argLine>
					<redirectTestOutputToFile>true</redirectTestOutputToFile>
					<failIfNoTests>false</failIfNoTests>
					<showEclipseLog>true</showEclipseLog>
					<useUIHarness>true</useUIHarness>
					<includes>
          				<include>**/*Test.java</include>
			        </includes>
				</configuration>
			</plugin>
			 -->
			
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<showEclipseLog>true</showEclipseLog>
					<useUIHarness>false</useUIHarness>
					<showEclipseLog>true</showEclipseLog>
					<failIfNoTests>true</failIfNoTests>
					<includes>
						<include>**/*Test.java</include>
						<include>**/*IT.java</include>
					</includes>
				</configuration>
			</plugin>
			
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<target>
						<artifact>
							<groupId>${project.groupId}</groupId>
							<artifactId>eclipse-435</artifactId>
							<version>${project.version}</version>
						</artifact>
					</target>
					<pomDependencies>consider</pomDependencies>
					<environments>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>x86_64</arch>
						</environment>
					</environments>
				</configuration>
			</plugin>

		</plugins>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.eclipse.tycho</groupId>
					<artifactId>tycho-packaging-plugin</artifactId>
					<version>${tycho.version}</version>
					<configuration>
						<format>yyyyMMdd-HHmm</format>
						<archive>
							<addMavenDescriptor>false</addMavenDescriptor>
						</archive>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>

	</build>

	<profiles>
		<profile>
			<id>platform-mac</id>
			<activation>
				<os>
					<family>mac</family>
				</os>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-surefire-plugin</artifactId>
						<version>${tycho.version}</version>
						<configuration>
							<argLine>-XstartOnFirstThread</argLine>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
